baseURL = "https://marioleone.me"
languageCode = "en-us"
title = "Mario Leone"
paginate = 5

[params]
    author = "Mario Leone"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
