baseURL = "https://mleone.dev"
theme = "ditalini"
languageCode = "en-us"
title = "Mario Leone"
paginate = 10

[params]
    author = "Mario Leone"
    profilePic = "/profilePic.jpeg"
    bio = "Hi, I'm Mario! Software engineering manager, actor, DIY-enthusiast. Trying new things every day and living life to the fullest!"
