baseURL = "https://mleone.dev"
theme = "ditalini"
languageCode = "en-us"
title = "Mario Leone"
paginate = 4

[params]
    author = "Mario Leone"
    profilePic = "profilePic.jpeg"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
